### ISSUE TITLE
Leadership Picture/Bio Order

### ISSUE THREAD

**Issue by oggnik** [Purdue-ACM/acm-website#27]
Not sure if it is intended (seems to be looking at the leadership.html code), but Ruihang's picture is under his bio in the leadership section.  Jonathan and Elliot's pictures are above their bios.  To me at least when I look at the page it looks weird...

**Comment by oggnik** [comment]
Ah, I see the issue.  My browser window wasn't big enough to trigger the col-lg tags.  Maybe we should make them col-md?

**Comment by baylessj** [comment]
Moving to md is a good start, but it looks like the main issue was the ordering of the columns. I referenced this SO post: https://stackoverflow.com/questions/20979062/bootstrap-right-column-on-top-on-mobile-view?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa and found a fix that seems to work well.
